services:
  database:
    image: mysql:8.0
    container_name: academic_event_mysql
    restart: always
    environment:
      MYSQL_DATABASE: "academic_event"
      MYSQL_USER: "base"
      MYSQL_PASSWORD: "base"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
